### ISSUE TITLE
Cant clone repo on local machine

### ISSUE THREAD

**Issue by nonfungibletunji** [HanielU/turbo-sk-payload#1]
``` stunjiturner@Musayb CodeReviewRepos % npx degit HanielU/turbo-sk-payload
! destination directory is not empty, aborting. Use options.force to override
stunjiturner@Musayb CodeReviewRepos % npx degit HanielU/turbo-sk-payload --force
> destination directory is not empty. Using --force, continuing
! could not find commit hash for master
stunjiturner@Musayb CodeReviewRepos % 
```
cant down load the repo, issuing the instructions in the readme

**Comment by hanielu** [comment]
@nonfungibletunji  I've updated the readme. (**Assuming you have git installed**) Try the following:
```bash
npx degit HanielU/turbo-sk-payload my-app # download the project

cd my-app # navigate into the project

pnpm install # install dependencies
```

**Comment by nonfungibletunji** [comment]
Yeah, I got it working… Thanks for the update? 

On Fri, 26 May 2023 04:33:54 GMT, Haniel Ubogu

***@***.*** wrote:

I've updated the readme. Try the following:

npx degit HanielU/turbo-sk-payload my-app # download the project cd my-app # navigate into the project pnpm install # install dependencies

— Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Sightuary

Everymedia Purification and Cultivation
